version: "3"

services:
  client:
    container_name: client
    image: node:16.15.1
    working_dir: /app
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    ports:
      - "8001:8001"
    command: sh -c "yarn && yarn start"
  server:
    container_name: server
    image: node:16.15.1
    working_dir: /app
    depends_on:
      - db
    ports:
      - "3003:3000"
    volumes:
      - ./server:/app
    command: sh -c "yarn && yarn start:dev"
  db:
    image: "mariadb:10.3"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: remitano
    ports:
      - "3307:3306"